services:
  - type: web
    name: harmony-habit-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir src main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false

